<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo base_url('assets') ?>/surat/style3.css" />
    <title>Laporan Absensi Harian</title>
  </head>
   <body>
	
	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<!-- <div style="width:128mm;float:left;">
						PT. Ditra Nusantara
					</div> -->
					<div style="width:128mm;float:right;">
						<p style="text-align:right;"><button style="text-align:right;" onclick="window.print()">Print</button></p>
						<p style="text-align:right;">Generated By System : <span><</span> <?php echo date('d/m/Y H:i:s') ?> <span>></span></p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
						<h3 style="margin:0px;"><b>Laporan Absensi Harian</b></h3>
					<hr/>
					
					<div style="width:128mm;float:left;">
						<p style="text-align:left; margin-top:-2px">Periode: 
						<?php echo date('d F Y',strtotime($tgl)); ?>
						<br/>
						
						</p>
					</div>
					<div style="clear:both;"></div>
					
					<center>
						<p style="font-weight:none;font-size:16pt">LAPORAN ABSENSI HARIAN</p>
					</center>
                    <table class="tb1" style="width: 100%;">
						<tr>
							<td rowspan="2">No</td>
							<td rowspan="2">NIK</td>
							<td rowspan="2">Nama</td>
							<td colspan="2"><center>Jam Absen</center></td>
						</tr>
						<tr>
							<td>Jam</td>
							<td>Status</td>
							<td>Jam</td>
							<td>Status</td>
							<td>Jam</td>
							<td>Status</td>
							<td>Jam</td>
							<td>Status</td>
						</tr>
						
						<?php                
                        $no = 0 ;
                        foreach($listData as $value){
                        $no++;
						?>
						<tr class="isi-colom">
							<td style="font-size:7pt;"><?php echo $no; ?></td>
							<td><?php echo $value['nik']; ?></td>
							<td style="text-align:left;">&nbsp;<?php echo $value['nama_lengkap']; ?></td>
							<?php 

							for($i=1;$i<5;$i++){
							$row = $this->m_monitoring->jadwal($value['id_jabatan'],$value['hari_log'],$i);
							$listDetail = $this->m_monitoring->getAllMonitoringByTipe($value['nik'],$value['waktu_log'],$i);
							
							
							?>
							<td><?php echo $listDetail['jam']; ?></td>
							<td>
							<?php 
							if(!empty($listDetail['jam'])){
								if($row['jam_mulai'] <= $listDetail['jam'] and $row['jam_selesai'] >= $listDetail['jam']){
									if($row['id_aktifitas'] == '1'){
										echo "Tepat Waktu";
									}else{
										echo "Sesuai Jadwal";
									}
								}else{	
									if($row['id_aktifitas'] == '1'){
										echo "Telat";
									}else{
										echo "Tidak Sesuai Jadwal";
									}
								}
							}
							?>
							</td>
							<?php } ?>
						</tr>                 
                        <?php } ?>
					</table>
				</div>
			</div>    
		</div>
	</div>
   
   </body>
</html>
</html>