<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo base_url('assets') ?>/surat/style3.css" />
    <title>Laporan Absensi Bulanan</title>
  </head>
   <body>
	
	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<div style="width:128mm;float:left;">
						PT. Ditra Nusantara
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;"><button style="text-align:right;" onclick="window.print()">Print</button></p>
						<p style="text-align:right;">Generated By System : <span><</span> <?php echo date('d/m/Y H:i:s') ?> <span>></span></p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
						<h3 style="margin:0px;"><b>Laporan Absensi Bulanan</b></h3>
					<hr/>
					
					<div style="width:128mm;float:left;">
						<p style="text-align:left; margin-top:-2px">Periode: 
						<?php echo date('F Y',strtotime('01-'.$bulan.'-'.$tahun)); ?>
						<br/>
						
						</p>
					</div>
					<div style="clear:both;"></div>
					
					<center>
						<p style="font-weight:none;font-size:16pt">LAPORAN ABSENSI BULANAN</p>
					</center>
                    <table class="tb1" style="width: 100%;">
						<tr>
							<td rowspan="2">No</td>
							<td rowspan="2">NIK</td>
							<td rowspan="2">Nama</td>
							<td colspan="4">Total</td>
						</tr>
						<tr>
							<td><center>Hari Kerja</center></td>
							<td><center>Jam Kerja</center></td>
							<td><center>Keterlambatan</center></td>
							<td><center>Over Time</center></td>
						</tr>
						
						<?php                
                        $no = 0 ;
                        foreach($listData as $value){
                        $no++;
						?>
						<tr class="isi-colom">
							<td style="font-size:7pt;"><?php echo $no; ?></td>
							<td><?php echo $value['nik']; ?></td>
							<td style="text-align:left;">&nbsp;<?php echo $value['nama_lengkap']; ?></td>
							<td><?php echo $value['hari_kerja']; ?></td>
							<td><?php echo $value['jam_kerja']; ?></td>
							<td>
							<?php 
							if(substr($value['jam_telat'],0,1) <> '-'){
								echo $value['jam_telat']; 
							}else{
								echo "-";
							}
							?>
							
							</td>
							<td><?php echo $value['jam_over']; ?></td>
						</tr>                 
                        <?php } ?>
					</table>
				</div>
			</div>    
		</div>
	</div>
   
   </body>
</html>
</html>