<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo base_url('assets') ?>/surat/style3.css" />
    <title>Laporan Gajihan</title>
  </head>
   <body>
	
	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<div style="width:128mm;float:left;">
						<img src="<?php echo base_url('assets') ?>/surat/logo.gif" style="visibility:hidden;" />
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;"><button style="text-align:right;" onclick="window.print()">Print</button></p>
						<p style="text-align:right;">Generated By System : <span><</span> <?php echo date('d/m/Y H:i:s') ?> <span>></span></p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
						<h3 style="margin:0px;"><b>Laporan Gajian</b></h3>
					<hr/>
					
					<div style="width:128mm;float:left;">
						<p style="text-align:left; margin-top:-2px">Periode: 
						<?php echo strtoupper(date('F Y',strtotime("15".'-'.$Bulan.'-'.$Tahun))); ?>
						<br/>
						
						</p>
					</div>
					<div style="clear:both;"></div>
					
					<center>
						<p style="font-weight:none;font-size:16pt">LAPORAN GAJIAN</p>
					</center>
                    <table class="tb1" style="width: 100%;">
						<tr>
							<td rowspan="2">No</td>
							<td rowspan="2">NIK</td>
							<td rowspan="2">Nama</td>
							<td rowspan="2">Gaji Pokok</td>
							<td colspan="4"><center>Penambahan</center></td>
							<td colspan="4"><center>Pengurangan (Biaya)</center></td>
							<td rowspan="2">Gaji Sebelum PPh 21</td>
							<td rowspan="2">Jumlah Penghasilan Netto/thn</td>
							<td rowspan="2">PTKP</td>
							<td rowspan="2">PKP</td>
							<td rowspan="2">PPH 21 Disetahunkan</td>
							<td rowspan="2">PPH 21 Yang Harus Dipotong</td>
							<td rowspan="2">Gaji Bersih</td>
						</tr>
						<tr>
							<td>Tunjangan Lainnya</td>
							<td>Premi Asuransi</td>
							<td>Imbalan Jasa Lainnya</td>
							<td>Bonus dan THR</td>
							<td>Biaya Jabatan</td>
							<td>Iuran Pensiun/THT</td>
							<td>Biaya Keterlambatan</td>
							<td>Biaya dari bonus dan THR</td>
						</tr>
						
						<?php
                                        
                        $no = 0 ;
                        $totalPajak = 0;
                        $totalNetto = 0;
                        foreach($listData as $value){
                        $no++;
						$GajiPokok = $GajiPokok+$value['GajiPokok'];
						$TunjanganLainnya = $TunjanganLainnya+$value['TunjanganLainnya'];
						$PremiAsuransi = $PremiAsuransi+$value['PremiAsuransi'];
						$Lembur = $Lembur+$value['Lembur'];
						$Bonus = $Bonus+$value['Bonus'];
						$BiayaJabatan = $BiayaJabatan+$value['BiayaJabatan'];
						$Iuran = $Iuran+$value['Iuran'];
						$PotonganTelat= $PotonganTelat+$value['PotonganTelat'];
						$BiayaBonus=$BiayaBonus+$value['BiayaBonus'];
						$TotalGajiBulan = $TotalGajiBulan+$value['TotalGajiBulan'];
						$TotalGajiNetto=$TotalGajiNetto+$value['TotalGajiNetto'];
						$NominalPKP=$NominalPKP+$value['NominalPKP'];
						$PKP = $PKP+$value['PKP'];
						$PphSetahun= $PphSetahun+$value['PphSetahun'];
						$PphSebulan=$PphSebulan+$value['PphSebulan'];
						$GajiSebulan = $GajiSebulan+ $value['TotalGajiBulan']-$value['PphSebulan'];
                        ?>
						
						<tr class="isi-colom">
							<td style="font-size:7pt;"><?php echo $no; ?></td>
							<td><?php echo $value['NIK']; ?></td>
							<td><?php echo $value['Namasiswa']; ?></td>
							<td><?php echo number_format($value['GajiPokok'],0,',','.'); ?></td>
							<td><?php echo number_format($value['TunjanganLainnya'],0,',','.'); ?></td>
							<td><?php echo number_format($value['PremiAsuransi'],0,',','.'); ?></td>
							<td><?php echo number_format($value['Lembur'],0,',','.'); ?></td>
							<td><?php echo number_format($value['Bonus'],0,',','.'); ?></td>
							<td><?php echo number_format($value['BiayaJabatan'],0,',','.'); ?></td>
							<td><?php echo number_format($value['Iuran'],0,',','.'); ?></td>
							<td><?php echo number_format($value['PotonganTelat'],0,',','.'); ?></td>
							<td><?php echo number_format($value['BiayaBonus'],0,',','.'); ?></td>
							<td><?php echo number_format($value['TotalGajiBulan'],0,',','.'); ?></td>
							<td><?php echo number_format($value['TotalGajiNetto'],0,',','.'); ?></td>
							<td><?php echo number_format($value['NominalPKP'],0,',','.'); ?></td>
							<td><?php echo number_format($value['PKP'],0,',','.'); ?></td>
							<td><?php echo number_format($value['PphSetahun'],0,',','.'); ?></td>
							<td><?php echo number_format($value['PphSebulan'],0,',','.'); ?></td>
							<td><?php echo number_format($value['TotalGajiBulan']-$value['PphSebulan'],0,',','.'); ?></td>
                            
						</tr>
                                             
                        <?php } ?>
                        <tr>
                    		<td style="font-size:7pt;" colspan="3" align="right">Total</td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($GajiPokok, 0,'.','.') ?></td> 
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($TunjanganLainnya, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($PremiAsuransi, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($Lembur, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($Bonus, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($BiayaJabatan, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($Iuran, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($PotonganTelat, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($BiayaBonus, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($TotalGajiBulan, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($TotalGajiNetto, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($NominalPKP, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($PKP, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($PphSetahun, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($PphSebulan, 0,'.','.') ?></td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($GajiSebulan, 0,'.','.') ?></td>  
                        </tr>
					</table>
				</div>
			</div>    
		</div>
	</div>
   
   </body>
</html>
</html>